version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install
  pre_build:
    commands:
      - npm run lint
      - npm run test
  build:
    commands:
      - echo 'Verifying npm publish is required'
      - CURRENT_PUBLISHED_VERSION=$(npm info adjs version)
      - if [ -z $CURRENT_PUBLISHED_VERSION ]; then echo "Could not find latest published version. Exiting build."; exit 1; fi
      - LOCAL_VERSION=$(node -e "console.log(require('./package.json').version)")
      - if [ -z $LOCAL_VERSION ]; then echo "Version is missing from package.json. Exiting build."; exit 1; fi
      - |
        set -e
        if [ $LOCAL_VERSION = $CURRENT_PUBLISHED_VERSION ]; then
          echo "Version is unchanged. NPM publish is not required."
        else
          echo "New version detected. Publishing to NPM."
          yum update -y
          yum install -y make glibc-devel gcc patch jq
          NPM_TOKEN=$(aws ssm get-parameter --name npm-publish-token --with-decryption | jq '.Parameter.Value') npm run release
        fi
