version: 0.2
# env:
#   variables:
#     STAGE: "production"

phases:
  install:
    commands:
      - npm install -g npm@latest
      - npm install
  pre_build:
      - npm run test
  # build:
  #   commands:
  #     - npm run release

