version: 0.2

phases:
  install:
    commands:
      - echo 'Beginning production build'
      - npm install -g npm@latest
      - npm install
  pre_build:
    commands:
      - npm run lint:no-fix
      - npm run test
  # build:
  #   commands:
  #     - npm run release

